version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "npm install; gulp"
    ports:
      - "80:80"
      - "5858:5858"
      - "8080:8080"
    volumes:
      - ./:/src/:rw
